[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/home.html"
  status = 200

[[redirects]]
  from = "/audit"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/chatgpt-ads"
  to = "/chatgpt-ads.html"
  status = 200

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 200

[[redirects]]
  from = "/services"
  to = "/services.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
